# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 010a854e22e47dc6c882ac20bd1c3020cc290d3ae9fc9c7341bc23cde0ba1fb96df8c2f8e9374276bb7a7cacb69a11be8178a620091ed459f7f9e9aa03d33e50

test:
  secret_key_base: 5980dc4482213799b90438e4b4a2b68e862c1b6f22fd234c3688d7131aae7d1e21fc5ab07f06bef50b1048eb66354d2dc3068facb98313e9964436d9117bfa78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
